version: '3.8'

services:
  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs-server
    privileged: true
    volumes:
      - nfs-data:/data
    environment:
      - SHARED_DIRECTORY=/data
    ports:
      - "2049:2049"

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KEYCLOAK_HOSTNAME=localhost
    command: start-dev
    volumes:
      - keycloak-data:/opt/keycloak/data

  node-app:
    image: node:18-alpine
    container_name: node-app
    build:
      context: ./app 
    ports:
      - "3000:3000" 
    environment:
      - NFS_MOUNT_PATH=/mnt/nfs
      - KEYCLOAK_HOSTNAME=http://keycloak:8080 # Add this if needed for runtime configuration
    depends_on:
      - nfs-server
      - keycloak
    volumes:
      - nfs-data:/mnt/nfs 

volumes:
  keycloak-data:
  nfs-data:
    driver: local
